// src/utilities/data.js
export const properties = [
    {
      id: 1,
      title: 'Modern Apartment',
      description: 'A beautiful apartment in the city center.',
      price: 120,
      image: 'https://via.placeholder.com/400x300?text=Modern+Apartment',
      location: 'New York, NY',
      bedrooms: 2,
      amenities: ['WiFi', 'Air Conditioning', 'Gym'],
    },
    {
      id: 2,
      title: 'Cozy Cottage',
      description: 'A quaint cottage in the countryside.',
      price: 80,
      image: 'https://via.placeholder.com/400x300?text=Cozy+Cottage',
      location: 'Lake Tahoe, CA',
      bedrooms: 3,
      amenities: ['Fireplace', 'Hot Tub', 'Lake View'],
    },
    {
      id: 3,
      title: 'Beachfront Villa',
      description: 'A luxurious villa with a private beach.',
      price: 300,
      image: 'https://via.placeholder.com/400x300?text=Beachfront+Villa',
      location: 'Malibu, CA',
      bedrooms: 4,
      amenities: ['Private Pool', 'Beach Access', 'Ocean View'],
    },
    {
      id: 4,
      title: 'Urban Loft',
      description: 'A chic loft in the heart of the city.',
      price: 150,
      image: 'https://via.placeholder.com/400x300?text=Urban+Loft',
      location: 'Chicago, IL',
      bedrooms: 1,
      amenities: ['WiFi', 'City View', 'Pet Friendly'],
    },
    {
      id: 5,
      title: 'Mountain Cabin',
      description: 'A rustic cabin with stunning mountain views.',
      price: 110,
      image: 'https://via.placeholder.com/400x300?text=Mountain+Cabin',
      location: 'Aspen, CO',
      bedrooms: 2,
      amenities: ['Fireplace', 'Ski-in/Ski-out', 'Hot Tub'],
    },
    {
      id: 6,
      title: 'Penthouse Suite',
      description: 'An opulent penthouse with a panoramic city view.',
      price: 400,
      image: 'https://via.placeholder.com/400x300?text=Penthouse+Suite',
      location: 'Miami, FL',
      bedrooms: 3,
      amenities: ['Private Terrace', 'Infinity Pool', 'Concierge Service'],
    },
    {
      id: 7,
      title: 'Country House',
      description: 'A charming country house with a large garden.',
      price: 90,
      image: 'https://via.placeholder.com/400x300?text=Country+House',
      location: 'Nashville, TN',
      bedrooms: 3,
      amenities: ['Garden', 'BBQ Grill', 'Family Friendly'],
    },
    {
      id: 8,
      title: 'Studio Apartment',
      description: 'A compact studio perfect for solo travelers.',
      price: 60,
      image: 'https://via.placeholder.com/400x300?text=Studio+Apartment',
      location: 'San Francisco, CA',
      bedrooms: 1,
      amenities: ['WiFi', 'Self Check-in', 'Central Location'],
    },
    {
      id: 9,
      title: 'Luxury Condo',
      description: 'A stylish condo with top-tier amenities.',
      price: 180,
      image: 'https://via.placeholder.com/400x300?text=Luxury+Condo',
      location: 'Los Angeles, CA',
      bedrooms: 2,
      amenities: ['Pool', 'Gym', '24/7 Security'],
    },
    {
      id: 10,
      title: 'Secluded Bungalow',
      description: 'A peaceful bungalow surrounded by nature.',
      price: 70,
      image: 'https://via.placeholder.com/400x300?text=Secluded+Bungalow',
      location: 'Portland, OR',
      bedrooms: 2,
      amenities: ['Fireplace', 'Hiking Trails', 'Pet Friendly'],
    },
  ];
  